"""Tests for config_tools.py. Do not edit this file — edit config_tools.py."""

import json
from pathlib import Path

import pytest

from config_tools import find_missing_keys, get_region, load_config, save_config

SAMPLE = Path(__file__).parent / "sample_config.json"


def test_load_config_reads_sample_file():
    config = load_config(SAMPLE)
    assert config["project"] == "sireesha-cloud-journey"
    assert config["owner"] == "sireesha"
    assert config["region"] == "us-east-1"
    assert "lambda" in config["services"]


def test_find_missing_keys_empty_when_complete():
    config = load_config(SAMPLE)
    assert find_missing_keys(config) == []


def test_find_missing_keys_lists_absent_in_order():
    assert find_missing_keys({"project": "x"}) == ["owner", "environment", "region"]


def test_find_missing_keys_handles_empty_dict():
    assert find_missing_keys({}) == ["project", "owner", "environment", "region"]


def test_get_region_returns_value():
    assert get_region({"region": "us-west-2"}) == "us-west-2"


def test_get_region_raises_when_missing():
    with pytest.raises(KeyError):
        get_region({"project": "x"})


def test_save_config_writes_json(tmp_path):
    path = tmp_path / "out.json"
    data = {"project": "demo", "owner": "sireesha"}
    save_config(path, data)

    loaded = json.loads(path.read_text())
    assert loaded == data
