"""Tests for fetch_json.py. Do not edit this file — edit fetch_json.py."""

from unittest.mock import Mock, patch

import pytest
import requests

from fetch_json import fetch_json, get_public_ip


def test_fetch_json_returns_parsed_dict():
    fake = Mock()
    fake.raise_for_status.return_value = None
    fake.json.return_value = {"ip": "1.2.3.4"}

    with patch("fetch_json.requests.get", return_value=fake) as get:
        result = fetch_json("https://example.com/json")

    get.assert_called_once()
    assert result == {"ip": "1.2.3.4"}


def test_fetch_json_raises_on_http_error():
    fake = Mock()
    fake.raise_for_status.side_effect = requests.HTTPError("boom")

    with patch("fetch_json.requests.get", return_value=fake):
        with pytest.raises(requests.HTTPError):
            fetch_json("https://example.com/missing")


def test_get_public_ip_reads_ip_field():
    with patch("fetch_json.fetch_json", return_value={"ip": "8.8.8.8"}):
        assert get_public_ip() == "8.8.8.8"
